# Generated by Django 5.1.1 on 2024-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('year_published', models.IntegerField()),
                ('authors', models.ManyToManyField(to='api.author')),
            ],
        ),
    ]
